import React, { useCallback } from "react";
import { TriggerBlock } from "../../types/schema";
import { useInteractionContext } from "../../hooks/useInteractionContext";
import { useQuizEngine } from "../../hooks/useQuizEngine";
import { useBlockState } from "../../hooks/useBlockState";
import { useStyleResolver } from "@/engine/hooks/useStyleResolver";
import { LogicEvaluator } from "../../core/LogicEvaluator";
import { logTest } from "@/lib/utils";
import { MarkdownText } from "../../utils/MarkdownText";

interface TriggerButtonProps {
  block: TriggerBlock;
}

export const TriggerButton: React.FC<TriggerButtonProps> = ({ block }) => {
  const { props } = block;
  const parentId = useInteractionContext();
  const { dispatch, engine } = useQuizEngine(); // Assuming we expose engine for context access

  // 1. SUBSCRIBE TO SELF (The Fix)
  // We need to see the computed state (disabled/hidden) calculated specifically for THIS block.
  // block.id is guaranteed to exist if you defined it in the schema. 
  // (If it was auto-generated by hydration, we'd need a way to pass that ID down, 
  // but your mock schema has explicit IDs).
  const selfState = useBlockState(block.id || "");

  // 2. Resolve Styles
  const { className, style } = useStyleResolver(props.styling);
  
  // 3. Computed State
  const isDisabled = selfState?.computed.disabled || props.disabled;
  
  // Base Tailwind Button Styles
  const baseClasses = `
    px-4 py-2 rounded font-medium transition-all
    ${isDisabled 
      ? "bg-gray-300 text-gray-500 cursor-not-allowed" 
      : "bg-blue-600 text-white hover:bg-blue-700 active:transform active:scale-95"
    } 
    ${className}
  `;

  // 3. The Action Interpreter
  const handleClick = useCallback((e: React.MouseEvent) => {
    if (isDisabled) {
      e.preventDefault();
      return;
    }

    const eventLogic = props.events?.on_click;
    if (!eventLogic) return;

    // DELEGATION: Let the engine handle the complexity.
    // We pass the event logic and our own ID (or parentId) as the context scope.
    engine.executeLogicAction(eventLogic, parentId || block.id || "");

  }, [isDisabled, props.events, parentId, engine]);

  return (
    <button
      id={block.id}
      type="button"
      className={baseClasses}
      style={style}
      disabled={isDisabled}
      onClick={handleClick}
    >
      <MarkdownText content={props.label} variant="inline" />
    </button>
  );
};